#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#include <string>
#include <unordered_map>
#include "../cJSON/cJSON.h"

//接口返回码
#define STATUS_SUCCESS 200
#define STATUS_METHOD_NOT_ALLOWED 405
#define STATUS_INTERNAL_SERVER_ERROR 500
#define STATUS_BAD_REQUEST 400 
#define STATUS_UNAUTHORIZED 401
#define STATUS_FORBIDDEN 403
#define STATUS_NOT_FOUND 404
#define STATUS_SERVICE_UNAVAILABLE 503
#define STATUS_GATEWAY_TIMEOUT 504
#define STATUS_UNSUPPORTED_MEDIA_TYPE 415

// 业务返回码
#define RESPONSE_SUCCESS 1000
#define RESPONSE_INVALID_PARAMS 1001
#define RESPONSE_FILE_NOT_FOUND 1002
#define RESPONSE_FAILED_TO_PROCESS 1003
#define RESPONSE_LIBREOFFICE_CONN_FAILED 1004
#define RESPONSE_UNKNOWN_ERROR 1005
#define RESPONSE_FILE_ALREADY_EXISTS 1006
#define RESPONSE_FILE_ALREADY_OPENED 1007
#define RESPONSE_FILE_ALREADY_CLOSED 1008
#define RESPONSE_FILE_ALREADY_SAVED 1009
#define RESPONSE_FILE_ALREADY_EDITED 1010
#define RESPONSE_FILE_ALREADY_MODIFIED 1011
#define RESPONSE_FILE_ALREADY_ADDED 1012
#define RESPONSE_FILE_ALREADY_REMOVED 1013
#define RESPONSE_FILE_ALREADY_RENAMED 1014
#define RESPONSE_FILE_ALREADY_CONVERTED 1015
#define RESPONSE_FILE_ALREADY_DELETED 1016
#define RESPONSE_FILE_ALREADY_USED 1017
#define RESPONSE_FILE_ALREADY_TESTED 1018
#define RESPONSE_FILE_NAME_NOT_EMPTY 1019
#define RESPONSE_FILE_NAME_INVALID 1020
#define RESPONSE_FILE_NAME_TOO_LONG 1021
#define RESPONSE_FILE_NAME_TOO_SHORT 1022
#define RESPONSE_FILE_NAME_CONTAINS_INVALID_CHAR 1023
#define RESPONSE_FILE_NAME_CONTAINS_INVALID_NUMBER 1024
#define RESPONSE_FILE_INVALID_SIZE 1025
#define RESPONSE_FILE_INVALID_EXTENSION 1026
#define RESPONSE_FILE_INVALID_CONTENT 1027
#define RESPONSE_FILE_INVALID_NAME 1028
#define RESPONSE_FILE_IS_TOO_LARGE 1029
#define RESPONSE_FILE_IS_TOO_SMALL 1030
#define RESPONSE_FILE_TRANSFERRING_FAILED 1031
#define RESPONSE_FILE_ENCODING_FAILED 1032
#define RESPONSE_FILE_DECOMPRESS_FAILED 1033
#define RESPONSE_FILE_COMPRESS_FAILED 1034
#define RESPONSE_FILE_PARSING_FAILED 1035
#define RESPONSE_FILE_VALIDATING_FAILED 1036
#define RESPONSE_FILE_UPLOAD_FAILED 1037
#define RESPONSE_FILE_DOWNLOAD_FAILED 1038
#define RESPONSE_FILE_DELETING_FAILED 1039
#define RESPONSE_FILE_RENAMING_FAILED 1040
#define RESPONSE_FILE_COPYING_FAILED 1041
#define RESPONSE_FILE_MOVING_FAILED 1042
#define RESPONSE_FILE_SHARING_FAILED 1043
#define RESPONSE_FILE_UNSHARING_FAILED 1044
#define RESPONSE_FILE_PATH_NOT_FOUND 1045
class ErrorCodeManager {
public:
    static std::string getErrorMessage(int errorCode);
    static void setErrorMessage(cJSON *setToJson, int errorCode);
private:
    static const std::unordered_map<int, std::string> errorMessages;
};

#endif // ERROR_CODES_H
